// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC_ymTYCpbBMQb0pPE4IMZ5-9cJPUXIoE',
    appId: '1:461993133670:web:a3884c331364060081cfa7',
    messagingSenderId: '461993133670',
    projectId: 'flutter-crud-7744d',
    authDomain: 'flutter-crud-7744d.firebaseapp.com',
    storageBucket: 'flutter-crud-7744d.appspot.com',
    measurementId: 'G-7CJNT29907',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2ZEbaEcF7kBDYicGu1dFGB57LqewjIOI',
    appId: '1:461993133670:android:f7189c138110cf7d81cfa7',
    messagingSenderId: '461993133670',
    projectId: 'flutter-crud-7744d',
    storageBucket: 'flutter-crud-7744d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIcy30B9AoW1qr4XfdD6MiHetNgoHjgVI',
    appId: '1:461993133670:ios:f28966be52a58d5c81cfa7',
    messagingSenderId: '461993133670',
    projectId: 'flutter-crud-7744d',
    storageBucket: 'flutter-crud-7744d.appspot.com',
    iosBundleId: 'com.example.flutterCrud1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIcy30B9AoW1qr4XfdD6MiHetNgoHjgVI',
    appId: '1:461993133670:ios:414366c7c5ec201e81cfa7',
    messagingSenderId: '461993133670',
    projectId: 'flutter-crud-7744d',
    storageBucket: 'flutter-crud-7744d.appspot.com',
    iosBundleId: 'com.example.flutterCrud1.RunnerTests',
  );
}
